### PR TITLE
Fix for Jalam app showing pressure screen in Jalam app

### PR DESCRIPTION
**Pull request by adhilxavier**
Minor change updated UUID of Tracker. Tracker was using same UUIDs of Pressure Sensor unit

### CODE REVIEW

**Review by speethambaran — APPROVED** [review]
Looks okay. Please merge. 

Please make sure this change is reflected in the corresponding Product documentation also. 
@rajeevinfolitz @jeslin14082000

**Comment by adhilxavier** [comment]
Closing this PR @rajeevinfolitz pls update the documentation with the changes mentioned here.

**Comment by adhilxavier** [comment]
Deleting this branch since changes are merged to Release

**Comment by rajeevinfolitz** [comment]
Hi,

The changes made to firmware is updated on the project document.

Regards,
Rajeev



________________________________

**Pull request merged**
